### ISSUE TITLE
USB interface issue in dmesg

### ISSUE THREAD

**Issue by venkisagunner93** [iron-ox/fadecandy_ros#23]
With the new C++ driver, I saw the following warning message pop up in `dmesg` when we start the `fadecandy_node`.

`[431653.276171] usb 1-4: usbfs: process 10226 (fadecandy_node) did not claim interface 0 before use`

To reproduce the issue, I restarted the `fadecandy_node` and looked up `dmesg`. Also, I saw the `INTERFACE_NO` assigned `0x01`. But why is the driver trying to claim `0x00`? 

https://github.com/iron-ox/fadecandy_ros/blob/fa4331a89c125fded54226f152f05a029cedce32/fadecandy_driver/src/fadecandy_driver.cpp#L45

https://github.com/iron-ox/fadecandy_ros/blob/fa4331a89c125fded54226f152f05a029cedce32/fadecandy_driver/src/fadecandy_driver.cpp#L86

**Comment by reinzor** [comment]
@jadhm FYI

**Comment by reinzor** [comment]
@jadhm , any updates on this?

**Comment by jadhm** [comment]
@reinzor  @venkisagunner93  It's on my planning this week. I will look at it as soon as possible.

**Comment by jadhm** [comment]
@reinzor @venkisagunner93  I looked today at this issue ... the bug was in the interface number itself ... the default interface of the fadecandy device is `0x00` which also has the endpoint `1`. I tested it and it works fine without any issues. I sent a pull request #24 with the correct interface number. @venkisagunner93  Could you please test it and let me know how it goes. Thanks in advance.

**Comment by venkisagunner93** [comment]
@jadhm I will test your fix this week. Thanks!
